services:
  backend:
    build: ./backend
    container_name: zoosanmarino-backend
    ports:
      - "5050:5050" # Puerto expuesto para la API .NET
    networks:
      - red-local
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: zoosanmarino-frontend
    ports:
      - "4200:80" # Puerto donde se sirve Angular con NGINX
    networks:
      - red-local
    depends_on:
      - backend
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  db:
    image: postgres:15
    container_name: zoosanmarino-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: zoo
    ports:
      - "5432:5432" # Puerto para conectar desde pgAdmin o el backend
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - red-local

volumes:
  pgdata:

networks:
  red-local:
    driver: bridge
